//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from calculator.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="calculatorParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface IcalculatorVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.expressionResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionResult([NotNull] calculatorParser.ExpressionResultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] calculatorParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.type_argument_list_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_argument_list_opt([NotNull] calculatorParser.Type_argument_list_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.variable_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_reference([NotNull] calculatorParser.Variable_referenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_list([NotNull] calculatorParser.Argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] calculatorParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.argument_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_name([NotNull] calculatorParser.Argument_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.argument_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_value([NotNull] calculatorParser.Argument_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expression([NotNull] calculatorParser.Primary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.primary_expression_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expression_start([NotNull] calculatorParser.Primary_expression_startContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.bracket_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket_expression([NotNull] calculatorParser.Bracket_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.simple_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_name([NotNull] calculatorParser.Simple_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.parenthesized_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesized_expression([NotNull] calculatorParser.Parenthesized_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.member_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_access([NotNull] calculatorParser.Member_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.predefined_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredefined_type([NotNull] calculatorParser.Predefined_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_list([NotNull] calculatorParser.Expression_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.this_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThis_access([NotNull] calculatorParser.This_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.object_or_collection_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_or_collection_initializer([NotNull] calculatorParser.Object_or_collection_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.object_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_initializer([NotNull] calculatorParser.Object_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.member_initializer_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_initializer_list([NotNull] calculatorParser.Member_initializer_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.member_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_initializer([NotNull] calculatorParser.Member_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.initializer_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer_value([NotNull] calculatorParser.Initializer_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.collection_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollection_initializer([NotNull] calculatorParser.Collection_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.element_initializer_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_initializer_list([NotNull] calculatorParser.Element_initializer_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.element_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_initializer([NotNull] calculatorParser.Element_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.member_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_declarator_list([NotNull] calculatorParser.Member_declarator_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.member_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_declarator([NotNull] calculatorParser.Member_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.unbound_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnbound_type_name([NotNull] calculatorParser.Unbound_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.generic_dimension_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_dimension_specifier([NotNull] calculatorParser.Generic_dimension_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.commas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommas([NotNull] calculatorParser.CommasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.checked_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChecked_expression([NotNull] calculatorParser.Checked_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.unchecked_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnchecked_expression([NotNull] calculatorParser.Unchecked_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_expression([NotNull] calculatorParser.Unary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.cast_disambiguation_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCast_disambiguation_token([NotNull] calculatorParser.Cast_disambiguation_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.pre_increment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPre_increment_expression([NotNull] calculatorParser.Pre_increment_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.pre_decrement_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPre_decrement_expression([NotNull] calculatorParser.Pre_decrement_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.multiplicative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicative_expression([NotNull] calculatorParser.Multiplicative_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.additive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditive_expression([NotNull] calculatorParser.Additive_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_expression([NotNull] calculatorParser.Shift_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.relational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational_expression([NotNull] calculatorParser.Relational_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.shift_disambiguation_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_disambiguation_token([NotNull] calculatorParser.Shift_disambiguation_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.is_disambiguation_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIs_disambiguation_token([NotNull] calculatorParser.Is_disambiguation_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.equality_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquality_expression([NotNull] calculatorParser.Equality_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_expression([NotNull] calculatorParser.And_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.exclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusive_or_expression([NotNull] calculatorParser.Exclusive_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.inclusive_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusive_or_expression([NotNull] calculatorParser.Inclusive_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.conditional_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_and_expression([NotNull] calculatorParser.Conditional_and_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.conditional_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_or_expression([NotNull] calculatorParser.Conditional_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.null_coalescing_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull_coalescing_expression([NotNull] calculatorParser.Null_coalescing_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_expression([NotNull] calculatorParser.Conditional_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] calculatorParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_operator([NotNull] calculatorParser.Assignment_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] calculatorParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.non_assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_assignment_expression([NotNull] calculatorParser.Non_assignment_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_expression([NotNull] calculatorParser.Constant_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.boolean_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_expression([NotNull] calculatorParser.Boolean_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.variable_declarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declarators([NotNull] calculatorParser.Variable_declaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.variable_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declarator([NotNull] calculatorParser.Variable_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.variable_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_initializer([NotNull] calculatorParser.Variable_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.rank_specifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRank_specifiers([NotNull] calculatorParser.Rank_specifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.rank_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRank_specifier([NotNull] calculatorParser.Rank_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.dim_separators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDim_separators([NotNull] calculatorParser.Dim_separatorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.array_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_initializer([NotNull] calculatorParser.Array_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.variable_initializer_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_initializer_list([NotNull] calculatorParser.Variable_initializer_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.from_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrom_contextual_keyword([NotNull] calculatorParser.From_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.let_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLet_contextual_keyword([NotNull] calculatorParser.Let_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.where_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhere_contextual_keyword([NotNull] calculatorParser.Where_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.join_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_contextual_keyword([NotNull] calculatorParser.Join_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.on_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOn_contextual_keyword([NotNull] calculatorParser.On_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.equals_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquals_contextual_keyword([NotNull] calculatorParser.Equals_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.into_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInto_contextual_keyword([NotNull] calculatorParser.Into_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.orderby_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderby_contextual_keyword([NotNull] calculatorParser.Orderby_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.ascending_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAscending_contextual_keyword([NotNull] calculatorParser.Ascending_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.descending_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescending_contextual_keyword([NotNull] calculatorParser.Descending_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.select_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_contextual_keyword([NotNull] calculatorParser.Select_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.group_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_contextual_keyword([NotNull] calculatorParser.Group_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.by_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBy_contextual_keyword([NotNull] calculatorParser.By_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.partial_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartial_contextual_keyword([NotNull] calculatorParser.Partial_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.alias_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias_contextual_keyword([NotNull] calculatorParser.Alias_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.yield_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYield_contextual_keyword([NotNull] calculatorParser.Yield_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.get_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGet_contextual_keyword([NotNull] calculatorParser.Get_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.set_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_contextual_keyword([NotNull] calculatorParser.Set_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.add_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd_contextual_keyword([NotNull] calculatorParser.Add_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.remove_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemove_contextual_keyword([NotNull] calculatorParser.Remove_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.dynamic_contextual_keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDynamic_contextual_keyword([NotNull] calculatorParser.Dynamic_contextual_keywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.arglist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArglist([NotNull] calculatorParser.ArglistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.right_arrow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_arrow([NotNull] calculatorParser.Right_arrowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.right_shift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_shift([NotNull] calculatorParser.Right_shiftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.right_shift_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_shift_assignment([NotNull] calculatorParser.Right_shift_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] calculatorParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.boolean_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_literal([NotNull] calculatorParser.Boolean_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword([NotNull] calculatorParser.KeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.method_invocation2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_invocation2([NotNull] calculatorParser.Method_invocation2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="calculatorParser.object_creation_expression2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_creation_expression2([NotNull] calculatorParser.Object_creation_expression2Context context);
}
