//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from calculator.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IcalculatorListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class calculatorBaseListener : IcalculatorListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.expressionResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionResult([NotNull] calculatorParser.ExpressionResultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.expressionResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionResult([NotNull] calculatorParser.ExpressionResultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] calculatorParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] calculatorParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.type_argument_list_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_argument_list_opt([NotNull] calculatorParser.Type_argument_list_optContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.type_argument_list_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_argument_list_opt([NotNull] calculatorParser.Type_argument_list_optContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.variable_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_reference([NotNull] calculatorParser.Variable_referenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.variable_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_reference([NotNull] calculatorParser.Variable_referenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument_list([NotNull] calculatorParser.Argument_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument_list([NotNull] calculatorParser.Argument_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] calculatorParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] calculatorParser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.argument_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument_name([NotNull] calculatorParser.Argument_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.argument_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument_name([NotNull] calculatorParser.Argument_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.argument_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument_value([NotNull] calculatorParser.Argument_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.argument_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument_value([NotNull] calculatorParser.Argument_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary_expression([NotNull] calculatorParser.Primary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary_expression([NotNull] calculatorParser.Primary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary_expression_start([NotNull] calculatorParser.Primary_expression_startContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.primary_expression_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary_expression_start([NotNull] calculatorParser.Primary_expression_startContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.bracket_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBracket_expression([NotNull] calculatorParser.Bracket_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.bracket_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBracket_expression([NotNull] calculatorParser.Bracket_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.simple_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_name([NotNull] calculatorParser.Simple_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.simple_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_name([NotNull] calculatorParser.Simple_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.parenthesized_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesized_expression([NotNull] calculatorParser.Parenthesized_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.parenthesized_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesized_expression([NotNull] calculatorParser.Parenthesized_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.member_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_access([NotNull] calculatorParser.Member_accessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.member_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_access([NotNull] calculatorParser.Member_accessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.predefined_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredefined_type([NotNull] calculatorParser.Predefined_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.predefined_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredefined_type([NotNull] calculatorParser.Predefined_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_list([NotNull] calculatorParser.Expression_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_list([NotNull] calculatorParser.Expression_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.this_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThis_access([NotNull] calculatorParser.This_accessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.this_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThis_access([NotNull] calculatorParser.This_accessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.object_or_collection_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_or_collection_initializer([NotNull] calculatorParser.Object_or_collection_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.object_or_collection_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_or_collection_initializer([NotNull] calculatorParser.Object_or_collection_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.object_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_initializer([NotNull] calculatorParser.Object_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.object_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_initializer([NotNull] calculatorParser.Object_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.member_initializer_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_initializer_list([NotNull] calculatorParser.Member_initializer_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.member_initializer_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_initializer_list([NotNull] calculatorParser.Member_initializer_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.member_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_initializer([NotNull] calculatorParser.Member_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.member_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_initializer([NotNull] calculatorParser.Member_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.initializer_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializer_value([NotNull] calculatorParser.Initializer_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.initializer_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializer_value([NotNull] calculatorParser.Initializer_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.collection_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollection_initializer([NotNull] calculatorParser.Collection_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.collection_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollection_initializer([NotNull] calculatorParser.Collection_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.element_initializer_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement_initializer_list([NotNull] calculatorParser.Element_initializer_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.element_initializer_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement_initializer_list([NotNull] calculatorParser.Element_initializer_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.element_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement_initializer([NotNull] calculatorParser.Element_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.element_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement_initializer([NotNull] calculatorParser.Element_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.member_declarator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_declarator_list([NotNull] calculatorParser.Member_declarator_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.member_declarator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_declarator_list([NotNull] calculatorParser.Member_declarator_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.member_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_declarator([NotNull] calculatorParser.Member_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.member_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_declarator([NotNull] calculatorParser.Member_declaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.unbound_type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnbound_type_name([NotNull] calculatorParser.Unbound_type_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.unbound_type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnbound_type_name([NotNull] calculatorParser.Unbound_type_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.generic_dimension_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_dimension_specifier([NotNull] calculatorParser.Generic_dimension_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.generic_dimension_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_dimension_specifier([NotNull] calculatorParser.Generic_dimension_specifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.commas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommas([NotNull] calculatorParser.CommasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.commas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommas([NotNull] calculatorParser.CommasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.checked_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChecked_expression([NotNull] calculatorParser.Checked_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.checked_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChecked_expression([NotNull] calculatorParser.Checked_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.unchecked_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnchecked_expression([NotNull] calculatorParser.Unchecked_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.unchecked_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnchecked_expression([NotNull] calculatorParser.Unchecked_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_expression([NotNull] calculatorParser.Unary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_expression([NotNull] calculatorParser.Unary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.cast_disambiguation_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCast_disambiguation_token([NotNull] calculatorParser.Cast_disambiguation_tokenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.cast_disambiguation_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCast_disambiguation_token([NotNull] calculatorParser.Cast_disambiguation_tokenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.pre_increment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPre_increment_expression([NotNull] calculatorParser.Pre_increment_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.pre_increment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPre_increment_expression([NotNull] calculatorParser.Pre_increment_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.pre_decrement_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPre_decrement_expression([NotNull] calculatorParser.Pre_decrement_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.pre_decrement_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPre_decrement_expression([NotNull] calculatorParser.Pre_decrement_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.multiplicative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicative_expression([NotNull] calculatorParser.Multiplicative_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.multiplicative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicative_expression([NotNull] calculatorParser.Multiplicative_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.additive_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditive_expression([NotNull] calculatorParser.Additive_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.additive_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditive_expression([NotNull] calculatorParser.Additive_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.shift_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShift_expression([NotNull] calculatorParser.Shift_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.shift_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShift_expression([NotNull] calculatorParser.Shift_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.relational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelational_expression([NotNull] calculatorParser.Relational_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.relational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelational_expression([NotNull] calculatorParser.Relational_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.shift_disambiguation_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShift_disambiguation_token([NotNull] calculatorParser.Shift_disambiguation_tokenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.shift_disambiguation_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShift_disambiguation_token([NotNull] calculatorParser.Shift_disambiguation_tokenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.is_disambiguation_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIs_disambiguation_token([NotNull] calculatorParser.Is_disambiguation_tokenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.is_disambiguation_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIs_disambiguation_token([NotNull] calculatorParser.Is_disambiguation_tokenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.equality_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquality_expression([NotNull] calculatorParser.Equality_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.equality_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquality_expression([NotNull] calculatorParser.Equality_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_expression([NotNull] calculatorParser.And_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_expression([NotNull] calculatorParser.And_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.exclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExclusive_or_expression([NotNull] calculatorParser.Exclusive_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.exclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExclusive_or_expression([NotNull] calculatorParser.Exclusive_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.inclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclusive_or_expression([NotNull] calculatorParser.Inclusive_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.inclusive_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclusive_or_expression([NotNull] calculatorParser.Inclusive_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.conditional_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_and_expression([NotNull] calculatorParser.Conditional_and_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.conditional_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_and_expression([NotNull] calculatorParser.Conditional_and_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.conditional_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_or_expression([NotNull] calculatorParser.Conditional_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.conditional_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_or_expression([NotNull] calculatorParser.Conditional_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.null_coalescing_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNull_coalescing_expression([NotNull] calculatorParser.Null_coalescing_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.null_coalescing_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNull_coalescing_expression([NotNull] calculatorParser.Null_coalescing_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.conditional_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_expression([NotNull] calculatorParser.Conditional_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.conditional_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_expression([NotNull] calculatorParser.Conditional_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] calculatorParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] calculatorParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_operator([NotNull] calculatorParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_operator([NotNull] calculatorParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] calculatorParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] calculatorParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.non_assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNon_assignment_expression([NotNull] calculatorParser.Non_assignment_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.non_assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNon_assignment_expression([NotNull] calculatorParser.Non_assignment_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.constant_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant_expression([NotNull] calculatorParser.Constant_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.constant_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant_expression([NotNull] calculatorParser.Constant_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.boolean_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_expression([NotNull] calculatorParser.Boolean_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.boolean_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_expression([NotNull] calculatorParser.Boolean_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.variable_declarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_declarators([NotNull] calculatorParser.Variable_declaratorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.variable_declarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_declarators([NotNull] calculatorParser.Variable_declaratorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.variable_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_declarator([NotNull] calculatorParser.Variable_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.variable_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_declarator([NotNull] calculatorParser.Variable_declaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.variable_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_initializer([NotNull] calculatorParser.Variable_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.variable_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_initializer([NotNull] calculatorParser.Variable_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.rank_specifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRank_specifiers([NotNull] calculatorParser.Rank_specifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.rank_specifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRank_specifiers([NotNull] calculatorParser.Rank_specifiersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.rank_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRank_specifier([NotNull] calculatorParser.Rank_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.rank_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRank_specifier([NotNull] calculatorParser.Rank_specifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.dim_separators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDim_separators([NotNull] calculatorParser.Dim_separatorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.dim_separators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDim_separators([NotNull] calculatorParser.Dim_separatorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.array_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_initializer([NotNull] calculatorParser.Array_initializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.array_initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_initializer([NotNull] calculatorParser.Array_initializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.variable_initializer_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_initializer_list([NotNull] calculatorParser.Variable_initializer_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.variable_initializer_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_initializer_list([NotNull] calculatorParser.Variable_initializer_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.from_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrom_contextual_keyword([NotNull] calculatorParser.From_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.from_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrom_contextual_keyword([NotNull] calculatorParser.From_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.let_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLet_contextual_keyword([NotNull] calculatorParser.Let_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.let_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLet_contextual_keyword([NotNull] calculatorParser.Let_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.where_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhere_contextual_keyword([NotNull] calculatorParser.Where_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.where_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhere_contextual_keyword([NotNull] calculatorParser.Where_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.join_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoin_contextual_keyword([NotNull] calculatorParser.Join_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.join_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoin_contextual_keyword([NotNull] calculatorParser.Join_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.on_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOn_contextual_keyword([NotNull] calculatorParser.On_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.on_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOn_contextual_keyword([NotNull] calculatorParser.On_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.equals_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquals_contextual_keyword([NotNull] calculatorParser.Equals_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.equals_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquals_contextual_keyword([NotNull] calculatorParser.Equals_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.into_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInto_contextual_keyword([NotNull] calculatorParser.Into_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.into_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInto_contextual_keyword([NotNull] calculatorParser.Into_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.orderby_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrderby_contextual_keyword([NotNull] calculatorParser.Orderby_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.orderby_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrderby_contextual_keyword([NotNull] calculatorParser.Orderby_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.ascending_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAscending_contextual_keyword([NotNull] calculatorParser.Ascending_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.ascending_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAscending_contextual_keyword([NotNull] calculatorParser.Ascending_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.descending_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDescending_contextual_keyword([NotNull] calculatorParser.Descending_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.descending_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDescending_contextual_keyword([NotNull] calculatorParser.Descending_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.select_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect_contextual_keyword([NotNull] calculatorParser.Select_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.select_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect_contextual_keyword([NotNull] calculatorParser.Select_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.group_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup_contextual_keyword([NotNull] calculatorParser.Group_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.group_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup_contextual_keyword([NotNull] calculatorParser.Group_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.by_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBy_contextual_keyword([NotNull] calculatorParser.By_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.by_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBy_contextual_keyword([NotNull] calculatorParser.By_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.partial_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartial_contextual_keyword([NotNull] calculatorParser.Partial_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.partial_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartial_contextual_keyword([NotNull] calculatorParser.Partial_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.alias_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlias_contextual_keyword([NotNull] calculatorParser.Alias_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.alias_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlias_contextual_keyword([NotNull] calculatorParser.Alias_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.yield_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYield_contextual_keyword([NotNull] calculatorParser.Yield_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.yield_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYield_contextual_keyword([NotNull] calculatorParser.Yield_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.get_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGet_contextual_keyword([NotNull] calculatorParser.Get_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.get_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGet_contextual_keyword([NotNull] calculatorParser.Get_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.set_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSet_contextual_keyword([NotNull] calculatorParser.Set_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.set_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSet_contextual_keyword([NotNull] calculatorParser.Set_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.add_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_contextual_keyword([NotNull] calculatorParser.Add_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.add_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_contextual_keyword([NotNull] calculatorParser.Add_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.remove_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemove_contextual_keyword([NotNull] calculatorParser.Remove_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.remove_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemove_contextual_keyword([NotNull] calculatorParser.Remove_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.dynamic_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDynamic_contextual_keyword([NotNull] calculatorParser.Dynamic_contextual_keywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.dynamic_contextual_keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDynamic_contextual_keyword([NotNull] calculatorParser.Dynamic_contextual_keywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.arglist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArglist([NotNull] calculatorParser.ArglistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.arglist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArglist([NotNull] calculatorParser.ArglistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.right_arrow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRight_arrow([NotNull] calculatorParser.Right_arrowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.right_arrow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRight_arrow([NotNull] calculatorParser.Right_arrowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.right_shift"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRight_shift([NotNull] calculatorParser.Right_shiftContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.right_shift"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRight_shift([NotNull] calculatorParser.Right_shiftContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.right_shift_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRight_shift_assignment([NotNull] calculatorParser.Right_shift_assignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.right_shift_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRight_shift_assignment([NotNull] calculatorParser.Right_shift_assignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] calculatorParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] calculatorParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.boolean_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_literal([NotNull] calculatorParser.Boolean_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.boolean_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_literal([NotNull] calculatorParser.Boolean_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword([NotNull] calculatorParser.KeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword([NotNull] calculatorParser.KeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.method_invocation2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_invocation2([NotNull] calculatorParser.Method_invocation2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.method_invocation2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_invocation2([NotNull] calculatorParser.Method_invocation2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calculatorParser.object_creation_expression2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_creation_expression2([NotNull] calculatorParser.Object_creation_expression2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calculatorParser.object_creation_expression2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_creation_expression2([NotNull] calculatorParser.Object_creation_expression2Context context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
